### ISSUE TITLE
Bug: Getting console error

### ISSUE THREAD

**Issue by tflx** [DennisvHest/vscode-npm-browser#49]
I'm getting this error in the VSCode console every time I open it.
It's version 1.1.4 on MacOs Ventura 13.00

It doens't matter if there is one or multiple package.jsons

```
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'selectedPackageJson')
I @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:701
deliver @ event.ts:908
fire @ event.ts:869
fire @ ipc.net.ts:671
Z.onmessage @ localProcessExtensionHost.ts:615
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read properties of undefined (reading 'selectedPackageJson')
    at Function.escapePackageJsonHtml (/Users/torben/.vscode/extensions/dennisvhest.npm-browser-1.1.4/bundle.js:2320:46)
    at BrowserWebView.getWebviewContent (/Users/torben/.vscode/extensions/dennisvhest.npm-browser-1.1.4/bundle.js:2288:80)
    at new BrowserWebView (/Users/torben/.vscode/extensions/dennisvhest.npm-browser-1.1.4/bundle.js:2233:41)
    at reinitializeBrowser (/Users/torben/.vscode/extensions/dennisvhest.npm-browser-1.1.4/bundle.js:19918:23)
    at /Users/torben/.vscode/extensions/dennisvhest.npm-browser-1.1.4/bundle.js:19961:9
    at Generator.next (<anonymous>)
    at /Users/torben/.vscode/extensions/dennisvhest.npm-browser-1.1.4/bundle.js:105:71
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/torben/.vscode/extensions/dennisvhest.npm-browser-1.1.4/bundle.js:101:12)
    at /Users/torben/.vscode/extensions/dennisvhest.npm-browser-1.1.4/bundle.js:19958:57
    at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at b.setVisible (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:16778)
    at g.$setVisible (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:13168)
    at l.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:11239)
    at l.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10957)
    at l.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10044)
    at l.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:9022)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:7810
    at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:15815
    at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:13941)
    at MessagePortMain.emit (node:events:526:28)
    at MessagePortMain.emit (node:domain:475:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364)
I @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:701
deliver @ event.ts:908
fire @ event.ts:869
fire @ ipc.net.ts:671
Z.onmessage @ localProcessExtensionHost.ts:615
log.ts:404   ERR Cannot read properties of undefined (reading 'selectedPackageJson'): TypeError: Cannot read properties of undefined (reading 'selectedPackageJson')
    at Function.escapePackageJsonHtml (/Users/torben/.vscode/extensions/dennisvhest.npm-browser-1.1.4/bundle.js:2320:46)
    at BrowserWebView.getWebviewContent (/Users/torben/.vscode/extensions/dennisvhest.npm-browser-1.1.4/bundle.js:2288:80)
    at new BrowserWebView (/Users/torben/.vscode/extensions/dennisvhest.npm-browser-1.1.4/bundle.js:2233:41)
    at reinitializeBrowser (/Users/torben/.vscode/extensions/dennisvhest.npm-browser-1.1.4/bundle.js:19918:23)
    at /Users/torben/.vscode/extensions/dennisvhest.npm-browser-1.1.4/bundle.js:19961:9
    at Generator.next (<anonymous>)
    at /Users/torben/.vscode/extensions/dennisvhest.npm-browser-1.1.4/bundle.js:105:71
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/torben/.vscode/extensions/dennisvhest.npm-browser-1.1.4/bundle.js:101:12)
    at /Users/torben/.vscode/extensions/dennisvhest.npm-browser-1.1.4/bundle.js:19958:57
    at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at b.setVisible (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:16778)
    at g.$setVisible (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:13168)
    at l.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:11239)
    at l.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10957)
    at l.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10044)
    at l.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:9022)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:7810
    at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:15815
    at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:13941)
    at MessagePortMain.emit (node:events:526:28)
    at MessagePortMain.emit (node:domain:475:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364)
```

**Comment by hanc2006** [comment]
same issue with my VSCode Insider
